# Generated by Django 4.2.4 on 2023-09-02 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='created_at',
            new_name='created',
        ),
    ]
